import { type NodeState } from '../types';

export const INITIAL_NODES: NodeState[] = [
  { id: 'START', name: '大本营', ownerId: null, basePrice: 0, currentPrice: 0, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'END', name: '敌军之腹', ownerId: null, basePrice: 0, currentPrice: 0, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },

  { id: 'n1', name: '荒地', ownerId: null, basePrice: 40, currentPrice: 40, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n2', name: '仙踪', ownerId: null, basePrice: 50, currentPrice: 50, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n3', name: '沼泽', ownerId: null, basePrice: 40, currentPrice: 40, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n4', name: '峭壁', ownerId: null, basePrice: 60, currentPrice: 60, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n5', name: '废墟', ownerId: null, basePrice: 40, currentPrice: 40, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n6', name: '古道', ownerId: null, basePrice: 50, currentPrice: 50, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n7', name: '幽谷', ownerId: null, basePrice: 40, currentPrice: 40, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n8', name: '龙巢', ownerId: null, basePrice: 60, currentPrice: 60, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n9', name: '迷雾', ownerId: null, basePrice: 40, currentPrice: 40, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n10', name: '剑冢', ownerId: null, basePrice: 50, currentPrice: 50, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n11', name: '熔炉', ownerId: null, basePrice: 40, currentPrice: 40, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n12', name: '深渊', ownerId: null, basePrice: 60, currentPrice: 60, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n13', name: '冰原', ownerId: null, basePrice: 40, currentPrice: 40, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n14', name: '雪峰', ownerId: null, basePrice: 50, currentPrice: 50, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n15', name: '遗迹', ownerId: null, basePrice: 40, currentPrice: 40, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n16', name: '星港', ownerId: null, basePrice: 60, currentPrice: 60, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n17', name: '暗巷', ownerId: null, basePrice: 40, currentPrice: 40, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n18', name: '钟塔', ownerId: null, basePrice: 50, currentPrice: 50, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n19', name: '密林', ownerId: null, basePrice: 40, currentPrice: 40, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n20', name: '神殿', ownerId: null, basePrice: 60, currentPrice: 60, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n21', name: '矿坑', ownerId: null, basePrice: 40, currentPrice: 40, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n22', name: '兵工厂', ownerId: null, basePrice: 50, currentPrice: 50, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n23', name: '堡垒', ownerId: null, basePrice: 40, currentPrice: 40, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n24', name: '祭坛', ownerId: null, basePrice: 60, currentPrice: 60, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n25', name: '长城', ownerId: null, basePrice: 40, currentPrice: 40, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n26', name: '孤岛', ownerId: null, basePrice: 50, currentPrice: 50, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n27', name: '港口', ownerId: null, basePrice: 40, currentPrice: 40, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n28', name: '高地', ownerId: null, basePrice: 60, currentPrice: 60, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n29', name: '隧道', ownerId: null, basePrice: 40, currentPrice: 40, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
  { id: 'n30', name: '要塞', ownerId: null, basePrice: 50, currentPrice: 50, captureCount: 0, captureHistory: [], isLocked: false, isStormLocked: false },
];

export const MAP_EDGES: [string, string][] = [
  ['START', 'n1'], ['START', 'n2'], ['START', 'n3'],
  ['n1', 'n4'], ['n1', 'n5'],
  ['n2', 'n5'], ['n2', 'n6'],
  ['n3', 'n6'], ['n3', 'n7'],
  ['n4', 'n8'], ['n4', 'n9'],
  ['n5', 'n9'], ['n5', 'n10'],
  ['n6', 'n10'], ['n6', 'n11'],
  ['n7', 'n11'], ['n7', 'n12'],
  ['n8', 'n13'],
  ['n9', 'n13'], ['n9', 'n14'],
  ['n10', 'n14'], ['n10', 'n15'],
  ['n11', 'n15'], ['n11', 'n16'],
  ['n12', 'n16'],
  ['n13', 'n17'], ['n13', 'n18'],
  ['n14', 'n18'], ['n14', 'n19'],
  ['n15', 'n19'], ['n15', 'n20'],
  ['n16', 'n20'], ['n16', 'n21'],
  ['n17', 'n22'],
  ['n18', 'n22'], ['n18', 'n23'],
  ['n19', 'n23'], ['n19', 'n24'],
  ['n20', 'n24'], ['n20', 'n25'],
  ['n21', 'n25'],
  ['n22', 'n26'], ['n22', 'n27'],
  ['n23', 'n27'], ['n23', 'n28'],
  ['n24', 'n28'], ['n24', 'n29'],
  ['n25', 'n29'], ['n25', 'n30'],
  ['n26', 'END'], ['n27', 'END'], ['n28', 'END'], ['n29', 'END'], ['n30', 'END'],
];

export const NODE_POSITIONS: Record<string, { x: number, y: number }> = {
  'START': { x: 50, y: 300 },
  'n1': { x: 150, y: 150 },
  'n2': { x: 150, y: 300 },
  'n3': { x: 150, y: 450 },
  'n4': { x: 250, y: 100 },
  'n5': { x: 250, y: 225 },
  'n6': { x: 250, y: 375 },
  'n7': { x: 250, y: 500 },
  'n8': { x: 350, y: 75 },
  'n9': { x: 350, y: 175 },
  'n10': { x: 350, y: 300 },
  'n11': { x: 350, y: 425 },
  'n12': { x: 350, y: 525 },
  'n13': { x: 450, y: 125 },
  'n14': { x: 450, y: 250 },
  'n15': { x: 450, y: 375 },
  'n16': { x: 450, y: 500 },
  'n17': { x: 550, y: 100 },
  'n18': { x: 550, y: 200 },
  'n19': { x: 550, y: 325 },
  'n20': { x: 550, y: 450 },
  'n21': { x: 550, y: 550 },
  'n22': { x: 650, y: 150 },
  'n23': { x: 650, y: 275 },
  'n24': { x: 650, y: 400 },
  'n25': { x: 650, y: 525 },
  'n26': { x: 750, y: 100 },
  'n27': { x: 750, y: 225 },
  'n28': { x: 750, y: 350 },
  'n29': { x: 750, y: 475 },
  'n30': { x: 750, y: 600 },
  'END': { x: 900, y: 300 },
};
